### ISSUE TITLE
CORS for PAM Rest API service not functioning as expected

### ISSUE THREAD

**Issue by aka004db** [MicrosoftDocs/MIMDocs.nl-nl#18]
When accessing the REST api from a nontrusted domain, the user gets prompted as expected. When the url /api/pamresources/sessioninfo is called, correct information is returned.
When /api/pamresources/pamrequests is called, even after a prompt for authentication, the error "The caller was not authenticated by the service" is returned.

Why is it not possible to authenticate and use the PAM Rest API

Cheers

Arjan

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 33b44fc3-556a-d6ab-f196-0e4e801674d0
* Version Independent ID: b42beceb-85bc-5325-8aab-9106246ffa4e
* Content: [Details van de PAM REST-API-Service](https://docs.microsoft.com/nl-nl/microsoft-identity-manager/reference/privileged-access-management-rest-api-service-details#feedback)
* Content Source: [MIMDocs/reference/privileged-access-management-rest-api-service-details.md](https://github.com/MicrosoftDocs/MIMDocs.nl-nl/blob/live/MIMDocs/reference/privileged-access-management-rest-api-service-details.md)
* Service: **microsoft-identity-manager**
* Product: **identity-manager-2015**
* GitHub Login: @msmbaldwin
* Microsoft Alias: **mbaldwin**

**Comment by CeciAc** [comment]
Hello, @aka004db 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
